inputDir: input/

outputMap: |
  ./output/{{ .in | strings.ReplaceAll ".tmpl" "" }}

context:
  logprofile:
    url: ./logprofile.yaml
  members:
    url: ./memberprofiles.yaml
  general:
    url: ./generalconfig.yaml
